# Generated by Django 4.2.1 on 2023-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("message", models.CharField(max_length=1000)),
                ("payment_method", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Created"), (2, "Failed"), (3, "Completed")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ipn_id", models.CharField(max_length=100, null=True)),
                ("order_tracking_id", models.CharField(max_length=100, null=True)),
                ("currency", models.CharField(max_length=10, null=True)),
                ("mpesa_reference", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
