# Generated by Django 4.2.1 on 2023-05-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_no", models.IntegerField()),
                ("email", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("message", models.CharField(max_length=1000)),
                ("payment_method", models.IntegerField(choices=[(1, "Created")])),
                ("status", models.IntegerField(choices=[(1, "Created")])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ipn_id", models.CharField(max_length=100)),
            ],
        ),
    ]
