# Generated by Django 4.2.1 on 2023-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("request", models.CharField(max_length=1000)),
                ("desciption", models.CharField(max_length=10000)),
            ],
        ),
    ]
