# Generated by Django 4.2.1 on 2023-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="payment_method",
            field=models.IntegerField(choices=[(1, "Created")], null=True),
        ),
        migrations.AlterField(
            model_name="gift",
            name="status",
            field=models.IntegerField(choices=[(1, "Created")], default=1),
        ),
    ]
