# Generated by Django 4.2.1 on 2023-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0002_alter_gift_payment_method_alter_gift_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="order_tracking_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gift",
            name="ipn_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
