# Generated by Django 4.2.1 on 2023-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0003_gift_order_tracking_id_alter_gift_ipn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="payment_method",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gift",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Cancelled"),
                    (3, "Processing"),
                    (4, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
