# Generated by Django 4.2.1 on 2023-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0004_alter_gift_payment_method_alter_gift_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="currency",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
