# Generated by Django 4.2.1 on 2023-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0005_gift_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "Failed"),
                    (3, "Processing"),
                    (4, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
