# Generated by Django 4.2.1 on 2023-05-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0006_alter_gift_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="email",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="gift",
            name="last_name",
        ),
    ]
