# Generated by Django 4.2.1 on 2023-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0008_alter_gift_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="mpesa_reference",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
